### ISSUE TITLE
Discrepancy between the output of pc algorithm in dodiscover and pgmpy graphs

### ISSUE THREAD

**Issue by Jaswanth-007** [py-why/dodiscover#121]
Hi, I have been working on a project that involves using the PC algorithm to learn causal structures from data and I am currently using both DoDiscover and Pgmpy packages for it. I have noticed that when I run the PC algorithm in both packages, the resulting graphs are not the same.

Can someone help me understand why there is a discrepancy in the output?

Thanks in advance for your help!

**Comment by jaron-lee** [comment]
Hi Jalla,

I have found that in general a lot of constraint based algorithms are quite susceptible to returning different outputs. This is because there are arbitrary choices that have to be made in terms of the order that conditional independence tests are run. This makes no difference theoretically speaking, but in practice what happens is that the results of the earlier tests will influence what tests are run later on. As a result you should expect that the resulting graphs are not the same.

In my own work I have even encountered implementations that return different results when run _on the same data_! I hope at least this has not been an issue for you. 

Thanks for using the package!

**Comment by adam2392** [comment]
@JallaJaswanth do you mind sharing some details about your dataset or even a small working example?

What CI test are you using?

**Comment by JallaJaswanth** [comment]
Sure @adam2392 
Thank you for your response. I am using the moviedataset available on Kaggle, You can find the dataset and more information about it here: https://www.kaggle.com/code/sachinsarkar/movielens-movie-recommendation-system
And I'm using GSquareCITest.

**Comment by adam2392** [comment]
Ah I see. 

If you're interested, a PR to the documentation explaining this potential discrepancy would be welcome!

**Comment by adam2392** [comment]
Also @JallaJaswanth would you mind posting the actual code and maybe pdf/svg or screenshot of the graphs that you obtain from both packages? It would be a great help! Perhaps there is a discrepancy not due to ordering of tests

**Comment by adam2392** [comment]
Another comment I have after perusing pgmpy code is that our skeleton discovery algorithm has a lot more flexibility built in. Moreover, the default parameters are different between pgmpy and dodiscover:

- pgmpy: https://pgmpy.org/structure_estimator/pc.html
- dodiscover: https://www.pywhy.org/dodiscover/dev/generated/dodiscover.constraint.PC.html

The main reason I could think of is the `max_cond_set_size=5` in pgmpy, whereas it is unbounded in our defaults.
